### ISSUE TITLE
Does not work with react native 0.56

### ISSUE THREAD

**Issue by reynaldlee** [nguyenhuynghia/react-native-global-font#2]
Hi,

Something change under the hood with Text component in react-native 0.56.
I got "cannot get property of undefined" error.
However, removing prototype from Text.prototype.render make it works again.

Best Regards.

**Comment by reynaldlee** [comment]
Fixed on latest commit

**Comment by jenni-divvito** [comment]
Just wanted to chime in with the full error message to make this more google-able because I just spent hours trying to figure out what was causing this and global font was the last thing I expected to be related.

```
TypeError: Cannot read property 'render' of undefined

This error is located at:
    in App (at renderApplication.js:32)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)
```
