### ISSUE TITLE
Not working on TextInput components

### ISSUE THREAD

**Issue by mojabyte** [nguyenhuynghia/react-native-global-font#4]
Custom fonts not working on TextInput components.

**Comment by rahulrk1991** [comment]
Guys any resolution on this? I'm having the same problem.

**Comment by ManigandanRaamanathan** [comment]
@HassanMojab any solution?

**Comment by mojabyte** [comment]
@ManigandanRaamanathan use [react-native-global-props](https://github.com/Ajackster/react-native-global-props) instead.

**Comment by ManigandanRaamanathan** [comment]
> @ManigandanRaamanathan use [react-native-global-props](https://github.com/Ajackster/react-native-global-props) instead.

@HassanMojab  could You Please provide the code snippet and the file content location where i need to add those codes for the global props library? I'm confused

**Comment by mojabyte** [comment]
@ManigandanRaamanathan sorry!
You may better to ask the owner.

**Comment by nguyenhuynghia** [comment]
I've check with RN 0.64, it's working ok. Please check
