### ISSUE TITLE
This module doesn't support React Native 0.62.x + 

### ISSUE THREAD

**Issue by retyui** [nguyenhuynghia/react-native-global-font#8]
Since RN 0.62.x TextInput is a [Function Component](https://github.com/facebook/react-native/blob/b9944e54ae35c2beed0e78ea454d871e0fe92ec6/Libraries/Components/TextInput/TextInput.js#L839)

And a monkey patching of .render() method doesn't work

https://github.com/nguyenhuynghia/react-native-global-font/blob/681f5973abfd31791744b41749e2487edcad0d4f/index.js#L18-L26

**Comment by nguyenhuynghia** [comment]
I've checked in RN 0.64.x, it's worked ok. please check
